// <auto-generated />
using System;
using HRPotter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HRPotter.Migrations
{
    [DbContext(typeof(HRPotterContext))]
    [Migration("20191206190010_UsersMigration")]
    partial class UsersMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HRPotter.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Google"
                        },
                        new
                        {
                            Id = 4,
                            Name = "EBR-IT"
                        });
                });

            modelBuilder.Entity("HRPotter.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("bit");

                    b.Property<int>("JobOfferId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId");

                    b.HasIndex("LastName");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
                            Email = "johnson@nsa.gov",
                            FirstName = "Stefan",
                            IsStudent = false,
                            JobOfferId = 2,
                            LastName = "Johnson",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "smith@nsa.gov",
                            FirstName = "Bogdan",
                            IsStudent = false,
                            JobOfferId = 3,
                            LastName = "Smith",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CvUrl = "https://www.google.com/",
                            Email = "miller@nsa.gov",
                            FirstName = "Ambroży",
                            IsStudent = true,
                            JobOfferId = 5,
                            LastName = "Miller",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "jones@nsa.gov",
                            FirstName = "Bogusław",
                            IsStudent = false,
                            JobOfferId = 6,
                            LastName = "Jones",
                            Phone = "555444333",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "wilson@nsa.gov",
                            FirstName = "Lech",
                            IsStudent = false,
                            JobOfferId = 1,
                            LastName = "Wilson",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "williams@nsa.gov",
                            FirstName = "Orfeusz",
                            IsStudent = false,
                            JobOfferId = 2,
                            LastName = "Williams",
                            Phone = "222333111",
                            Status = 1
                        });
                });

            modelBuilder.Entity("HRPotter.Models.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalaryFrom")
                        .HasColumnType("int");

                    b.Property<int?>("SalaryTo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTitle");

                    b.ToTable("JobOffers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 282, DateTimeKind.Local).AddTicks(5258),
                            Description = "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
                            JobTitle = "Backend Developer",
                            Location = "Warsaw",
                            SalaryTo = 15000
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 2,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(196),
                            Description = "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
                            JobTitle = "Frontend Developer",
                            Location = "Warsaw",
                            SalaryFrom = 10000,
                            ValidUntil = new DateTime(2019, 12, 16, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(245)
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1393),
                            JobTitle = "Manager",
                            Location = "New York",
                            SalaryFrom = 15000,
                            SalaryTo = 25000,
                            ValidUntil = new DateTime(2019, 12, 11, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1407)
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1432),
                            Description = "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
                            JobTitle = "Teacher",
                            Location = "Paris",
                            SalaryFrom = 10000,
                            SalaryTo = 15000
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 4,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1443),
                            Description = "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum",
                            JobTitle = "Cook",
                            Location = "Venice",
                            SalaryFrom = 10000,
                            SalaryTo = 15000
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1452),
                            JobTitle = "Manager",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 2,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1457),
                            JobTitle = "Tst1",
                            Location = "Venice",
                            SalaryFrom = 4000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1461),
                            JobTitle = "Tst2",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1465),
                            JobTitle = "Tst3",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1469),
                            JobTitle = "Tst4",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1473),
                            JobTitle = "Tst5",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1477),
                            JobTitle = "Tst6",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1481),
                            JobTitle = "Tst7",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1485),
                            JobTitle = "Tst8",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 1,
                            Created = new DateTime(2019, 12, 6, 20, 0, 10, 285, DateTimeKind.Local).AddTicks(1489),
                            JobTitle = "Tst9",
                            Location = "Venice",
                            SalaryFrom = 15000,
                            SalaryTo = 25000
                        });
                });

            modelBuilder.Entity("HRPotter.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "HRUser"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("HRPotter.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("B2CKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRPotter.Models.JobApplication", b =>
                {
                    b.HasOne("HRPotter.Models.JobOffer", "JobOffer")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPotter.Models.JobOffer", b =>
                {
                    b.HasOne("HRPotter.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPotter.Models.User", b =>
                {
                    b.HasOne("HRPotter.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
