version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release ./HRPotter/HRPotter.csproj --output ./publish
      - aws s3 sync --delete ./publish/wwwroot "s3://staticcontenthrpotter"
      - aws cloudfront create-invalidation  --distribution-id E2UYJC12YD4NQY --paths "/js/*"
      - export BUCKET=publishbuildsbucket
      - aws cloudformation package --template-file serverless-template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  files:
    - serverless-template.yml
    - outputtemplate.yml